export const PPT_STYLE_OPTIONS = [
  {
    id: "magazine",
    group: "归藏 · 电子杂志",
    name: "墨水经典",
    family: "magazine",
    description: "克制杂志版式、衬线感标题、暖色强调，适合人文分享和综合汇报。",
    shell: "#ece7dc",
    bg: "FBFAF6",
    ink: "1F2933",
    muted: "687076",
    line: "D8CFBD",
    accent: "A65F2B",
    accentText: "FFF7ED",
    tableFill: "FFFDF8",
    cardFill: "FFF7ED",
    font: "'Noto Serif SC', 'Microsoft YaHei', serif",
    guide: "电子杂志 × 电子墨水。类似 Monocle 的克制版式，衬线感标题、细线、强留白、暖色强调。适合人文分享、行业观察、综合工作汇报。",
  },
  {
    id: "magazineIndigo",
    group: "归藏 · 电子杂志",
    name: "靛蓝瓷",
    family: "magazine",
    description: "靛蓝强调、瓷白底色，适合研究、制度解读和数据化汇报。",
    shell: "#e8edf2",
    bg: "FBFCFE",
    ink: "172033",
    muted: "5B6678",
    line: "C8D5E3",
    accent: "315D8C",
    accentText: "FFFFFF",
    tableFill: "F7FAFD",
    cardFill: "EAF2FA",
    font: "'Noto Serif SC', 'Microsoft YaHei', serif",
    guide: "电子杂志靛蓝主题。瓷白底色、靛蓝强调、衬线标题和细线分隔，适合研究报告、政策解读、数据化汇报。",
  },
  {
    id: "magazineForest",
    group: "归藏 · 电子杂志",
    name: "森林墨",
    family: "magazine",
    description: "深绿墨色、自然克制，适合校园文化、德育、美育和可持续主题。",
    shell: "#e6ece5",
    bg: "FBFCF6",
    ink: "1E2A24",
    muted: "61706A",
    line: "CBD8C9",
    accent: "2E6B4E",
    accentText: "FFFFFF",
    tableFill: "FAFCF6",
    cardFill: "ECF5EE",
    font: "'Noto Serif SC', 'Microsoft YaHei', serif",
    guide: "电子杂志森林主题。深绿墨色、自然克制、留白充分，适合校园文化、德育、美育、可持续与活动复盘。",
  },
  {
    id: "magazineKraft",
    group: "归藏 · 电子杂志",
    name: "牛皮纸",
    family: "magazine",
    description: "复古纸感、低饱和棕红，适合历史、校史、文化和故事型分享。",
    shell: "#eadfcd",
    bg: "FBF7EF",
    ink: "2D241F",
    muted: "756A5D",
    line: "D9C8AD",
    accent: "9A4E3B",
    accentText: "FFF8F1",
    tableFill: "FFF8EE",
    cardFill: "F3E5D0",
    font: "'Noto Serif SC', 'Microsoft YaHei', serif",
    guide: "电子杂志牛皮纸主题。复古纸感、低饱和棕红和衬线标题，适合校史、文化、故事型分享。",
  },
  {
    id: "magazineDune",
    group: "归藏 · 电子杂志",
    name: "沙丘",
    family: "magazine",
    description: "沙色纸底、黑金强调，适合艺术、设计、创意和展陈类内容。",
    shell: "#e9e0cf",
    bg: "FCF8EE",
    ink: "25221B",
    muted: "756D5D",
    line: "D8CCB5",
    accent: "B87A2B",
    accentText: "FFF8EA",
    tableFill: "FFF9EC",
    cardFill: "F4E8D2",
    font: "'Noto Serif SC', 'Microsoft YaHei', serif",
    guide: "电子杂志沙丘主题。沙色纸底、黑金强调和艺术杂志感排版，适合艺术、设计、创意和展陈类内容。",
  },
  {
    id: "swiss",
    group: "归藏 · 瑞士国际主义",
    name: "IKB 蓝",
    family: "swiss",
    description: "瑞士网格、蓝色强调，适合科技、数据和工程化汇报。",
    shell: "#e5e7eb",
    bg: "FFFFFF",
    ink: "111827",
    muted: "64748B",
    line: "CBD5E1",
    accent: "0057B8",
    accentText: "FFFFFF",
    tableFill: "F8FAFC",
    cardFill: "F8FAFC",
    font: "Arial, 'Microsoft YaHei', sans-serif",
    guide: "瑞士国际主义 IKB 蓝。无衬线、网格系统、极细分割线、单一高亮色、直角纯色块。适合科技产品、数据汇报、年度总结。",
  },
  {
    id: "swissLemon",
    group: "归藏 · 瑞士国际主义",
    name: "柠檬黄",
    family: "swiss",
    description: "黑白网格配柠檬黄强调，适合醒目的发布、动员和重点提示。",
    shell: "#eceff1",
    bg: "FFFFFF",
    ink: "111111",
    muted: "5F6670",
    line: "C7CDD4",
    accent: "F5D400",
    accentText: "111111",
    tableFill: "FAFAF5",
    cardFill: "FFF9C7",
    font: "Arial, 'Microsoft YaHei', sans-serif",
    guide: "瑞士国际主义柠檬黄。黑白网格、极细线条和单一黄色高亮，适合发布会、动员部署、重点提示。",
  },
  {
    id: "swissLime",
    group: "归藏 · 瑞士国际主义",
    name: "柠檬绿",
    family: "swiss",
    description: "网格系统配清亮绿色，适合创新、课程改革和项目推进。",
    shell: "#edf2ef",
    bg: "FFFFFF",
    ink: "111827",
    muted: "63706B",
    line: "C9D5CE",
    accent: "8BC34A",
    accentText: "10200D",
    tableFill: "FAFCF8",
    cardFill: "EEF8E4",
    font: "Arial, 'Microsoft YaHei', sans-serif",
    guide: "瑞士国际主义柠檬绿。清亮绿色强调、网格分栏和数据化表达，适合创新项目、课程改革、项目推进。",
  },
  {
    id: "swissOrange",
    group: "归藏 · 瑞士国际主义",
    name: "安全橙",
    family: "swiss",
    description: "安全橙强调、强对比网格，适合安全、应急、流程和风险主题。",
    shell: "#f0ece7",
    bg: "FFFFFF",
    ink: "111827",
    muted: "6B6470",
    line: "D2CBC4",
    accent: "FF6B00",
    accentText: "FFFFFF",
    tableFill: "FFF9F4",
    cardFill: "FFF0E6",
    font: "Arial, 'Microsoft YaHei', sans-serif",
    guide: "瑞士国际主义安全橙。强对比、直角色块和清晰流程感，适合安全教育、应急预案、风险排查和流程说明。",
  },
  {
    id: "officialBlue",
    group: "公文 / 汇报",
    name: "蓝白庄重",
    family: "official",
    description: "蓝白底色、庄重清晰，适合正式公文、工作汇报、制度说明。",
    shell: "#e8eef5",
    bg: "FFFFFF",
    ink: "172033",
    muted: "5F6B7A",
    line: "CAD6E3",
    accent: "1F5F99",
    accentText: "FFFFFF",
    tableFill: "F7FAFD",
    cardFill: "EEF5FB",
    font: "'Microsoft YaHei', Arial, sans-serif",
    guide: "公文蓝白庄重风格。以蓝白为主、结构清楚、标题正式、文字密度适中，适合工作汇报、制度说明、通知解读、会议汇报。",
  },
  {
    id: "officialRed",
    group: "公文 / 汇报",
    name: "政务红金",
    family: "official",
    description: "红金强调、正式稳重，适合党建、政务、表彰和活动总结。",
    shell: "#f1e8e3",
    bg: "FFFCF8",
    ink: "2B1D1C",
    muted: "735F5B",
    line: "E1C9BE",
    accent: "B42318",
    accentText: "FFFFFF",
    tableFill: "FFF7F2",
    cardFill: "FCEBE6",
    font: "'Microsoft YaHei', Arial, sans-serif",
    guide: "政务红金风格。红色强调、金色暖底、正式稳重，适合党建学习、政务汇报、表彰总结、重要活动复盘。",
  },
  {
    id: "educationGreen",
    group: "公文 / 汇报",
    name: "校园青绿",
    family: "official",
    description: "青绿清爽、亲和克制，适合校园教务、德育、培训和活动方案。",
    shell: "#e8f2ef",
    bg: "FFFFFF",
    ink: "17302C",
    muted: "5A706A",
    line: "C8DDD7",
    accent: "0F766E",
    accentText: "FFFFFF",
    tableFill: "F8FCFB",
    cardFill: "EAF7F4",
    font: "'Microsoft YaHei', Arial, sans-serif",
    guide: "校园青绿风格。青绿色强调、亲和清爽、版式克制，适合教务安排、德育活动、培训方案、校园项目汇报。",
  },
  {
    id: "reportSlate",
    group: "公文 / 汇报",
    name: "深蓝灰总结",
    family: "official",
    description: "深蓝灰、数据优先，适合年度总结、述职、绩效和阶段复盘。",
    shell: "#e7ebef",
    bg: "FBFCFD",
    ink: "17212B",
    muted: "607080",
    line: "CAD3DC",
    accent: "244C73",
    accentText: "FFFFFF",
    tableFill: "F6F8FA",
    cardFill: "EAF0F5",
    font: "'Microsoft YaHei', Arial, sans-serif",
    guide: "深蓝灰总结风格。沉稳、数据优先、强调关键结论，适合年度总结、述职汇报、绩效复盘、阶段性工作报告。",
  },
  {
    id: "trainingWarm",
    group: "公文 / 汇报",
    name: "暖灰培训",
    family: "official",
    description: "暖灰橙强调，适合培训课件、方案说明和行动清单。",
    shell: "#ede9e3",
    bg: "FFFEFA",
    ink: "252525",
    muted: "6B6258",
    line: "DAD2C8",
    accent: "C56A2A",
    accentText: "FFFFFF",
    tableFill: "FFF9F2",
    cardFill: "F8EDE1",
    font: "'Microsoft YaHei', Arial, sans-serif",
    guide: "暖灰培训风格。暖灰底色、橙色强调、行动导向，适合培训课件、方案解读、流程说明和任务清单。",
  },
  {
    id: "custom",
    group: "自定义",
    name: "自定义风格",
    family: "custom",
    description: "由使用者填写风格描述，可保存为 PPT 执笔人。",
    shell: "#eef2f3",
    bg: "FFFEFB",
    ink: "172026",
    muted: "56616B",
    line: "C8D0D6",
    accent: "0F766E",
    accentText: "FFFFFF",
    tableFill: "F9FBFA",
    cardFill: "ECFDF5",
    font: "'Microsoft YaHei', Arial, sans-serif",
    guide: "自定义风格。保持原生 PPTX 可编辑，不依赖网页效果、截图、外部字体或本机路径。",
  },
];

export function getPptStyleOption(style) {
  const id = normalizePptStyleId(style);
  return PPT_STYLE_OPTIONS.find((option) => option.id === id) || PPT_STYLE_OPTIONS[0];
}

export function normalizePptStyleId(style) {
  const value = String(style || "").trim();
  const aliases = {
    swissIkb: "swiss",
    swissikb: "swiss",
    swissBlue: "swiss",
    swissblue: "swiss",
    magazineInk: "magazine",
    magazineink: "magazine",
    official: "officialBlue",
    government: "officialBlue",
    school: "educationGreen",
  };
  const lowerValue = value.toLowerCase();
  const normalized = aliases[value] || aliases[lowerValue] || value;
  const option = PPT_STYLE_OPTIONS.find((item) => item.id === normalized || item.id.toLowerCase() === lowerValue);
  return option ? option.id : "magazine";
}

export function buildPptStyleGuide(style, styleDescription = "") {
  const option = getPptStyleOption(style);
  if (option.id === "custom") {
    return [
      "当前选择风格：自定义。",
      `用户风格描述：${String(styleDescription || "").trim() || "未填写，请在保持清晰、可编辑、正式演示感的前提下自行选择克制风格。"}`,
      "自定义风格也必须保持原生 PPTX 可编辑，不要依赖网页效果、截图、外部字体或本机路径。",
    ].join("\n");
  }

  return [
    `当前选择风格：${option.group} / ${option.name}。`,
    `风格说明：${option.description}`,
    `设计规则：${option.guide}`,
    "输出要求：仍然只输出可转换为原生 PPTX 的结构 JSON，不要生成 HTML、CSS、脚本、外部图片路径或网页交互效果。",
  ].join("\n");
}

export function getPreviewTheme(style) {
  const option = getPptStyleOption(style);
  return {
    shell: option.shell,
    bg: `#${option.bg}`,
    ink: `#${option.ink}`,
    muted: `#${option.muted}`,
    line: `#${option.line}`,
    accent: `#${option.accent}`,
    font: option.font,
  };
}

export function getPptxTheme(style) {
  const option = getPptStyleOption(style);
  return {
    name: option.id,
    family: option.family,
    bg: option.bg,
    ink: option.ink,
    muted: option.muted,
    line: option.line,
    accent: option.accent,
    accentText: option.accentText,
    tableFill: option.tableFill,
    cardFill: option.cardFill,
    titleFont: option.family === "swiss" ? "Arial" : "Microsoft YaHei",
    bodyFont: "Microsoft YaHei",
  };
}
